### ISSUE TITLE
sui 和vue  webpack一起使用报错：Failed to execute 'querySelectorAll' on 'Document': '#/' is not a valid selector

### ISSUE THREAD

**Issue by fancyecommerce** [sdc-alibaba/SUI-Mobile#981]
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#/' is not a valid selector.
    at Object.T.qsa (eval at <anonymous> (http://120.24.37.249:8080/app.js:1152:2), <anonymous>:145:211)
    at Array.find (eval at <anonymous> (http://120.24.37.249:8080/app.js:1152:2), <anonymous>:237:35)
    at i._init (eval at <anonymous> (http://120.24.37.249:8080/app.js:1146:2), <anonymous>:1488:46)
    at new i (eval at <anonymous> (http://120.24.37.249:8080/app.js:1146:2), <anonymous>:1480:110)
    at eval (eval at <anonymous> (http://120.24.37.249:8080/app.js:1146:2), <anonymous>:1597:27)
    at HTMLDocument.eval (eval at <anonymous> (http://120.24.37.249:8080/app.js:1152:2), <anonymous>:189:9)
T.qsa @ zepto.min.js?504f:2
find @ zepto.min.js?504f:2
i._init @ sm.min.js?5bc8:10
i @ sm.min.js?5bc8:10
(anonymous) @ sm.min.js?5bc8:10
(anonymous) @ zepto.min.js?504f:2

**Comment by LeeLejia** [comment]
很莫名奇妙，不知道情况是不是和我的一样，我删除了标签中page的class就可以了。

**Comment by zhangxiaochunxy** [comment]
是因为router冲突了，禁用router就可以。在zepto之后添加如下代码就可以。<script type="text/javascript">
     $.config = {
       router: false
     }
   </script>
希望能帮到你。
